### ISSUE TITLE
Second Weyl point in Te

### ISSUE THREAD

**Issue by maximiliandaschner** [rubel75/BerryPI#10]
This isn't an issue but more a general question about "Tutorial 6: Weyl point characterization in Te". I am fairly new to this field and I was wondering whether we shouldn't expect a second Weyl point in Te since they usually come in pairs. The Weyl point that we found here is at Gamma, and I am wondering where I should expect the Weyl point with opposite chirality to be located at.

**Comment by rubel75** [comment]
I can only refer to the paper by Stepan Tsirkin et al. (https://doi.org/10.1103/PhysRevB.96.045102) and suggest to get in touch with Stepan (Materials Physics Center, San Sebastian, Spain).
