### ISSUE TITLE
LinAlgError

### ISSUE THREAD

**Issue by maximiliandaschner** [rubel75/BerryPI#11]
I've been trying to run WloopPHI.py, first on TaAs which worked fine, then on different materials, e.g. TaTe4. For the latter I receive the following error which I cannot resolve:

```
 LAPW1 END
13.269u 0.539s 0:13.97 98.7%	0+0k 11728+163416io 64pf+0w
 LAPW1 END
13.289u 0.575s 0:13.92 99.4%	0+0k 0+163416io 0pf+0w
LAPWSO END
13.801u 0.214s 0:14.08 99.5%	0+0k 8+385224io 0pf+0w
case_name=NbTe4
W2W END
0.261u 0.024s 0:00.29 96.5%	0+0k 0+40io 0pf+0w
case_name=NbTe4
W2W END
0.246u 0.028s 0:00.28 92.8%	0+0k 0+40io 0pf+0w
0.000u 0.005s 0:00.00 0.0%	0+0k 0+16io 0pf+0w
Traceback (most recent call last):
  File "/home/md/rds/WIEN2k/SRC_BerryPI/BerryPI/berrypi", line 1078, in <module>
    [bAutomationErrorChk,phasesRaw] = rawBerryPhase(configFile)
  File "/home/md/rds/WIEN2k/SRC_BerryPI/BerryPI/berrypi", line 759, in rawBerryPhase
    pathPhases = mmn2pathphase.main(args)
  File "/home/md/rds/WIEN2k/SRC_BerryPI/BerryPI/mmn2pathphase.py", line 267, in main
    leign, vect = numpy.linalg.eig(L)
  File "<__array_function__ internals>", line 6, in eig
  File "/home/md/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1317, in eig
    _assert_finite(a)
  File "/home/md/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 208, in _assert_finite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.LinAlgError: Array must not contain infs or NaNs
Output will also be written in NbTe4.outputberry
```

I've tried different locations in the Brillouin zone and various materials, but I end up with the same error above. Is this a known issue and if so, is there a solution to it? As the linalg-library is affected, it is quite difficult for me to see what the problem is and therefore any help would be highly appreciated!

**Comment by maximiliandaschner** [comment]
Turns out that this error only occurs if the number of k-points N in the Brillouin zone during the first initializaiton (`init_lapw -numk N`) is chose too large. For smaller N it seems to work fine.

**Comment by rubel75** [comment]
Would it be possible to send the WIEN2k case folder with all necessary files and the BerryPI command to reproduce the error? Thanks.
